/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-08-30 06:03:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/twtags.tld", Long.valueOf(1518498704000L));
    _jspx_dependants.put("/pages/../inc/taglib.inc", Long.valueOf(1518498698000L));
    _jspx_dependants.put("/pages/../inc/head.inc", Long.valueOf(1518498698000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fpanelGrid_0026_005fstyleClass_005fid_005fcolumns_005fcolumnClasses;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fpanelGroup;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fverbatim;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fgraphicImage_0026_005furl_005fstyleClass_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fpanelGroup_0026_005fstyle;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftitle_005fstyle_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftw_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005fpanelGrid_0026_005fstyleClass_005fid_005fcolumns_005fcolumnClasses = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005fpanelGroup = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005fverbatim = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005fgraphicImage_0026_005furl_005fstyleClass_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005fpanelGroup_0026_005fstyle = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftitle_005fstyle_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftw_005fview.release();
    _005fjspx_005ftagPool_005ftw_005fpanelGrid_0026_005fstyleClass_005fid_005fcolumns_005fcolumnClasses.release();
    _005fjspx_005ftagPool_005ftw_005fpanelGroup.release();
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.release();
    _005fjspx_005ftagPool_005ftw_005fverbatim.release();
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody.release();
    _005fjspx_005ftagPool_005ftw_005fgraphicImage_0026_005furl_005fstyleClass_005fnobody.release();
    _005fjspx_005ftagPool_005ftw_005fpanelGroup_0026_005fstyle.release();
    _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftitle_005fstyle_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t");
      //  tw:view
      com.sparta.common.view.tag.view.TWViewTag _jspx_th_tw_005fview_005f0 = (com.sparta.common.view.tag.view.TWViewTag) _005fjspx_005ftagPool_005ftw_005fview.get(com.sparta.common.view.tag.view.TWViewTag.class);
      boolean _jspx_th_tw_005fview_005f0_reused = false;
      try {
        _jspx_th_tw_005fview_005f0.setPageContext(_jspx_page_context);
        _jspx_th_tw_005fview_005f0.setParent(null);
        int _jspx_eval_tw_005fview_005f0 = _jspx_th_tw_005fview_005f0.doStartTag();
        if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tw_005fview_005f0);
          }
          do {
            out.write("\r\n");
            out.write("\t\t<head>\r\n");
            out.write("\t\t\t");
 response.setHeader("Cache-Control","no-cache"); 
            out.write("\r\n");
            out.write("<meta http-equiv=\"Page-Enter\" content=\"blendTrans(Duration=0.01)\">\r\n");
            out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/global.css\">\r\n");
            out.write("<link rel=\"icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\" />\r\n");
            out.write("<link rel=\"shortcut icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\" /> \r\n");
            out.write("<script type=\"text/javascript\" src=\"../js/util.js\"></script>\r\n");
            out.write("<script type=\"text/javascript\" src=\"../js/window.js\"></script>\r\n");
            out.write("<script type=\"text/javascript\">\r\n");
            out.write("\twindow.onresize = setGUIComponents;\r\n");
            out.write("</script>");
            out.write("\r\n");
            out.write("\t\t</head>\t\t\t\t\t \t\t \r\n");
            out.write("\t\t<body onload=\"loadKeyHandlers();\">\t   \r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_tw_005fpanelGrid_005f0(_jspx_th_tw_005fview_005f0, _jspx_page_context))
              return;
            out.write("\t\r\n");
            out.write("\t\t\t\t\t\t\t\t\t\t \t\t\t  \r\n");
            out.write("\t\t</body>\r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_tw_005fview_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_tw_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftw_005fview.reuse(_jspx_th_tw_005fview_005f0);
        _jspx_th_tw_005fview_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fview_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fview_005f0_reused);
      }
      out.write("\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tw_005fpanelGrid_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:panelGrid
    com.sparta.common.view.tag.panelGrid.TWPanelGridTag _jspx_th_tw_005fpanelGrid_005f0 = (com.sparta.common.view.tag.panelGrid.TWPanelGridTag) _005fjspx_005ftagPool_005ftw_005fpanelGrid_0026_005fstyleClass_005fid_005fcolumns_005fcolumnClasses.get(com.sparta.common.view.tag.panelGrid.TWPanelGridTag.class);
    boolean _jspx_th_tw_005fpanelGrid_005f0_reused = false;
    try {
      _jspx_th_tw_005fpanelGrid_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fpanelGrid_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fview_005f0);
      // /pages/footer.jsp(10,3) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fpanelGrid_005f0.setId("footer");
      // /pages/footer.jsp(10,3) name = styleClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fpanelGrid_005f0.setStyleClass("footer");
      // /pages/footer.jsp(10,3) name = columns type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fpanelGrid_005f0.setColumns("2");
      // /pages/footer.jsp(10,3) name = columnClasses type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fpanelGrid_005f0.setColumnClasses("left, right");
      int _jspx_eval_tw_005fpanelGrid_005f0 = _jspx_th_tw_005fpanelGrid_005f0.doStartTag();
      if (_jspx_eval_tw_005fpanelGrid_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_tw_005fpanelGroup_005f0(_jspx_th_tw_005fpanelGrid_005f0, _jspx_page_context))
          return true;
        out.write("\t\r\n");
        out.write("\t\t\t\t");
        if (_jspx_meth_tw_005fpanelGroup_005f1(_jspx_th_tw_005fpanelGrid_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t");
      }
      if (_jspx_th_tw_005fpanelGrid_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fpanelGrid_0026_005fstyleClass_005fid_005fcolumns_005fcolumnClasses.reuse(_jspx_th_tw_005fpanelGrid_005f0);
      _jspx_th_tw_005fpanelGrid_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fpanelGrid_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fpanelGrid_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005fpanelGroup_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:panelGroup
    com.sparta.common.view.tag.panelGroup.TWPanelGroupTag _jspx_th_tw_005fpanelGroup_005f0 = (com.sparta.common.view.tag.panelGroup.TWPanelGroupTag) _005fjspx_005ftagPool_005ftw_005fpanelGroup.get(com.sparta.common.view.tag.panelGroup.TWPanelGroupTag.class);
    boolean _jspx_th_tw_005fpanelGroup_005f0_reused = false;
    try {
      _jspx_th_tw_005fpanelGroup_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fpanelGroup_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGrid_005f0);
      int _jspx_eval_tw_005fpanelGroup_005f0 = _jspx_th_tw_005fpanelGroup_005f0.doStartTag();
      if (_jspx_eval_tw_005fpanelGroup_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("                    ");
        if (_jspx_meth_tw_005foutputText_005f0(_jspx_th_tw_005fpanelGroup_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_tw_005fverbatim_005f0(_jspx_th_tw_005fpanelGroup_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("                    ");
        if (_jspx_meth_tw_005foutputText_005f1(_jspx_th_tw_005fpanelGroup_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_tw_005foutputText_005f2(_jspx_th_tw_005fpanelGroup_005f0, _jspx_page_context))
          return true;
        if (_jspx_meth_tw_005foutputText_005f3(_jspx_th_tw_005fpanelGroup_005f0, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t");
      }
      if (_jspx_th_tw_005fpanelGroup_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fpanelGroup.reuse(_jspx_th_tw_005fpanelGroup_005f0);
      _jspx_th_tw_005fpanelGroup_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fpanelGroup_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fpanelGroup_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f0 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f0_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f0);
      // /pages/footer.jsp(12,20) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f0.setValue("#{GlobalMngdBean.applicationName}");
      int _jspx_eval_tw_005foutputText_005f0 = _jspx_th_tw_005foutputText_005f0.doStartTag();
      if (_jspx_th_tw_005foutputText_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.reuse(_jspx_th_tw_005foutputText_005f0);
      _jspx_th_tw_005foutputText_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005fverbatim_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:verbatim
    com.sun.faces.taglib.jsf_core.VerbatimTag _jspx_th_tw_005fverbatim_005f0 = (com.sun.faces.taglib.jsf_core.VerbatimTag) _005fjspx_005ftagPool_005ftw_005fverbatim.get(com.sun.faces.taglib.jsf_core.VerbatimTag.class);
    boolean _jspx_th_tw_005fverbatim_005f0_reused = false;
    try {
      _jspx_th_tw_005fverbatim_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fverbatim_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f0);
      int _jspx_eval_tw_005fverbatim_005f0 = _jspx_th_tw_005fverbatim_005f0.doStartTag();
      if (_jspx_eval_tw_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        if (_jspx_eval_tw_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tw_005fverbatim_005f0);
        }
        do {
          out.write("<sup style=\"font-size: 8px\">TM</sup>&nbsp;");
          int evalDoAfterBody = _jspx_th_tw_005fverbatim_005f0.doAfterBody();
          if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
            break;
        } while (true);
        if (_jspx_eval_tw_005fverbatim_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
          out = _jspx_page_context.popBody();
        }
      }
      if (_jspx_th_tw_005fverbatim_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fverbatim.reuse(_jspx_th_tw_005fverbatim_005f0);
      _jspx_th_tw_005fverbatim_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fverbatim_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fverbatim_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f1 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f1_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f0);
      // /pages/footer.jsp(13,20) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f1.setValue("VERSION");
      // /pages/footer.jsp(13,20) name = termType type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f1.setTermType("GENERIC_TEXT");
      // /pages/footer.jsp(13,20) name = termID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f1.setTermID("177");
      int _jspx_eval_tw_005foutputText_005f1 = _jspx_th_tw_005foutputText_005f1.doStartTag();
      if (_jspx_th_tw_005foutputText_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody.reuse(_jspx_th_tw_005foutputText_005f1);
      _jspx_th_tw_005foutputText_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f1, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f2 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f2_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f0);
      // /pages/footer.jsp(13,89) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f2.setValue("&nbsp;");
      int _jspx_eval_tw_005foutputText_005f2 = _jspx_th_tw_005foutputText_005f2.doStartTag();
      if (_jspx_th_tw_005foutputText_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.reuse(_jspx_th_tw_005foutputText_005f2);
      _jspx_th_tw_005foutputText_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f2, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f3(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f3 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f3_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f3.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f3.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f0);
      // /pages/footer.jsp(13,120) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f3.setValue("#{GlobalMngdBean.versionNumber}");
      int _jspx_eval_tw_005foutputText_005f3 = _jspx_th_tw_005foutputText_005f3.doStartTag();
      if (_jspx_th_tw_005foutputText_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.reuse(_jspx_th_tw_005foutputText_005f3);
      _jspx_th_tw_005foutputText_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f3, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005fpanelGroup_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGrid_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:panelGroup
    com.sparta.common.view.tag.panelGroup.TWPanelGroupTag _jspx_th_tw_005fpanelGroup_005f1 = (com.sparta.common.view.tag.panelGroup.TWPanelGroupTag) _005fjspx_005ftagPool_005ftw_005fpanelGroup.get(com.sparta.common.view.tag.panelGroup.TWPanelGroupTag.class);
    boolean _jspx_th_tw_005fpanelGroup_005f1_reused = false;
    try {
      _jspx_th_tw_005fpanelGroup_005f1.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fpanelGroup_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGrid_005f0);
      int _jspx_eval_tw_005fpanelGroup_005f1 = _jspx_th_tw_005fpanelGroup_005f1.doStartTag();
      if (_jspx_eval_tw_005fpanelGroup_005f1 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t\t ");
        if (_jspx_meth_tw_005fgraphicImage_005f0(_jspx_th_tw_005fpanelGroup_005f1, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t ");
        if (_jspx_meth_tw_005fpanelGroup_005f2(_jspx_th_tw_005fpanelGroup_005f1, _jspx_page_context))
          return true;
        out.write("\t\t\t\t\t\t\r\n");
        out.write("                ");
      }
      if (_jspx_th_tw_005fpanelGroup_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fpanelGroup.reuse(_jspx_th_tw_005fpanelGroup_005f1);
      _jspx_th_tw_005fpanelGroup_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fpanelGroup_005f1, _jsp_getInstanceManager(), _jspx_th_tw_005fpanelGroup_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005fgraphicImage_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:graphicImage
    com.sun.faces.taglib.html_basic.GraphicImageTag _jspx_th_tw_005fgraphicImage_005f0 = (com.sun.faces.taglib.html_basic.GraphicImageTag) _005fjspx_005ftagPool_005ftw_005fgraphicImage_0026_005furl_005fstyleClass_005fnobody.get(com.sun.faces.taglib.html_basic.GraphicImageTag.class);
    boolean _jspx_th_tw_005fgraphicImage_005f0_reused = false;
    try {
      _jspx_th_tw_005fgraphicImage_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fgraphicImage_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f1);
      // /pages/footer.jsp(16,6) name = url type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fgraphicImage_005f0.setUrl("../images/database.gif");
      // /pages/footer.jsp(16,6) name = styleClass type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fgraphicImage_005f0.setStyleClass("icon");
      int _jspx_eval_tw_005fgraphicImage_005f0 = _jspx_th_tw_005fgraphicImage_005f0.doStartTag();
      if (_jspx_th_tw_005fgraphicImage_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fgraphicImage_0026_005furl_005fstyleClass_005fnobody.reuse(_jspx_th_tw_005fgraphicImage_005f0);
      _jspx_th_tw_005fgraphicImage_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fgraphicImage_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fgraphicImage_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005fpanelGroup_005f2(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f1, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:panelGroup
    com.sparta.common.view.tag.panelGroup.TWPanelGroupTag _jspx_th_tw_005fpanelGroup_005f2 = (com.sparta.common.view.tag.panelGroup.TWPanelGroupTag) _005fjspx_005ftagPool_005ftw_005fpanelGroup_0026_005fstyle.get(com.sparta.common.view.tag.panelGroup.TWPanelGroupTag.class);
    boolean _jspx_th_tw_005fpanelGroup_005f2_reused = false;
    try {
      _jspx_th_tw_005fpanelGroup_005f2.setPageContext(_jspx_page_context);
      _jspx_th_tw_005fpanelGroup_005f2.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f1);
      // /pages/footer.jsp(17,6) name = style type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005fpanelGroup_005f2.setStyle("font-weight: bold");
      int _jspx_eval_tw_005fpanelGroup_005f2 = _jspx_th_tw_005fpanelGroup_005f2.doStartTag();
      if (_jspx_eval_tw_005fpanelGroup_005f2 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write("\r\n");
        out.write("\t\t\t\t\t\t ");
        if (_jspx_meth_tw_005foutputText_005f4(_jspx_th_tw_005fpanelGroup_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t ");
        if (_jspx_meth_tw_005foutputText_005f5(_jspx_th_tw_005fpanelGroup_005f2, _jspx_page_context))
          return true;
        out.write("\r\n");
        out.write("\t\t\t\t\t\t\t ");
        if (_jspx_meth_tw_005foutputText_005f6(_jspx_th_tw_005fpanelGroup_005f2, _jspx_page_context))
          return true;
        out.write("\t\t\t\t\t \r\n");
        out.write("\t\t\t\t\t");
      }
      if (_jspx_th_tw_005fpanelGroup_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005fpanelGroup_0026_005fstyle.reuse(_jspx_th_tw_005fpanelGroup_005f2);
      _jspx_th_tw_005fpanelGroup_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fpanelGroup_005f2, _jsp_getInstanceManager(), _jspx_th_tw_005fpanelGroup_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f4(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f4 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f4_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f4.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f4.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f2);
      // /pages/footer.jsp(18,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f4.setValue("DATABASE");
      // /pages/footer.jsp(18,7) name = termType type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f4.setTermType("GENERIC_TEXT");
      // /pages/footer.jsp(18,7) name = termID type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f4.setTermID("595");
      int _jspx_eval_tw_005foutputText_005f4 = _jspx_th_tw_005foutputText_005f4.doStartTag();
      if (_jspx_th_tw_005foutputText_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftermType_005ftermID_005fnobody.reuse(_jspx_th_tw_005foutputText_005f4);
      _jspx_th_tw_005foutputText_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f4, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f4_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f5(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f5 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f5_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f5.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f5.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f2);
      // /pages/footer.jsp(19,7) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f5.setValue(": ");
      int _jspx_eval_tw_005foutputText_005f5 = _jspx_th_tw_005foutputText_005f5.doStartTag();
      if (_jspx_th_tw_005foutputText_005f5.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005fnobody.reuse(_jspx_th_tw_005foutputText_005f5);
      _jspx_th_tw_005foutputText_005f5_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f5, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f5_reused);
    }
    return false;
  }

  private boolean _jspx_meth_tw_005foutputText_005f6(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fpanelGroup_005f2, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:outputText
    com.sparta.common.view.tag.outputText.TWOutputTextTag _jspx_th_tw_005foutputText_005f6 = (com.sparta.common.view.tag.outputText.TWOutputTextTag) _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftitle_005fstyle_005fnobody.get(com.sparta.common.view.tag.outputText.TWOutputTextTag.class);
    boolean _jspx_th_tw_005foutputText_005f6_reused = false;
    try {
      _jspx_th_tw_005foutputText_005f6.setPageContext(_jspx_page_context);
      _jspx_th_tw_005foutputText_005f6.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fpanelGroup_005f2);
      // /pages/footer.jsp(20,8) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f6.setValue("#{GlobalMngdBean.databaseName}");
      // /pages/footer.jsp(20,8) name = title type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f6.setTitle("#{GlobalMngdBean.databaseInfo}");
      // /pages/footer.jsp(20,8) name = style type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005foutputText_005f6.setStyle("cursor: default");
      int _jspx_eval_tw_005foutputText_005f6 = _jspx_th_tw_005foutputText_005f6.doStartTag();
      if (_jspx_th_tw_005foutputText_005f6.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005foutputText_0026_005fvalue_005ftitle_005fstyle_005fnobody.reuse(_jspx_th_tw_005foutputText_005f6);
      _jspx_th_tw_005foutputText_005f6_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005foutputText_005f6, _jsp_getInstanceManager(), _jspx_th_tw_005foutputText_005f6_reused);
    }
    return false;
  }
}
