/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.6
 * Generated at: 2018-08-30 06:03:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.pages;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class hiddenMainFrame_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/twtags.tld", Long.valueOf(1518498704000L));
    _jspx_dependants.put("/pages/../inc/taglib.inc", Long.valueOf(1518498698000L));
    _jspx_dependants.put("/pages/../inc/head.inc", Long.valueOf(1518498698000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005fview;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005ftw_005finputHidden_0026_005fvalue_005fid_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005ftw_005fview = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005ftw_005finputHidden_0026_005fvalue_005fid_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005ftw_005fview.release();
    _005fjspx_005ftagPool_005ftw_005finputHidden_0026_005fvalue_005fid_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("\t");
      //  tw:view
      com.sparta.common.view.tag.view.TWViewTag _jspx_th_tw_005fview_005f0 = (com.sparta.common.view.tag.view.TWViewTag) _005fjspx_005ftagPool_005ftw_005fview.get(com.sparta.common.view.tag.view.TWViewTag.class);
      boolean _jspx_th_tw_005fview_005f0_reused = false;
      try {
        _jspx_th_tw_005fview_005f0.setPageContext(_jspx_page_context);
        _jspx_th_tw_005fview_005f0.setParent(null);
        int _jspx_eval_tw_005fview_005f0 = _jspx_th_tw_005fview_005f0.doStartTag();
        if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
          if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = org.apache.jasper.runtime.JspRuntimeLibrary.startBufferedBody(_jspx_page_context, _jspx_th_tw_005fview_005f0);
          }
          do {
            out.write("\r\n");
            out.write("\t\t<head>\r\n");
            out.write("\t\t\t ");
 response.setHeader("Cache-Control","no-cache"); 
            out.write("\r\n");
            out.write("<meta http-equiv=\"Page-Enter\" content=\"blendTrans(Duration=0.01)\">\r\n");
            out.write("<link rel=\"stylesheet\" type=\"text/css\" href=\"../css/global.css\">\r\n");
            out.write("<link rel=\"icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\" />\r\n");
            out.write("<link rel=\"shortcut icon\" href=\"../images/favicon.ico\" type=\"image/x-icon\" /> \r\n");
            out.write("<script type=\"text/javascript\" src=\"../js/util.js\"></script>\r\n");
            out.write("<script type=\"text/javascript\" src=\"../js/window.js\"></script>\r\n");
            out.write("<script type=\"text/javascript\">\r\n");
            out.write("\twindow.onresize = setGUIComponents;\r\n");
            out.write("</script>");
            out.write("\r\n");
            out.write("\t\t\t <script type=\"text/javascript\">\r\n");
            out.write("\t\t\t \t  var _skipPageChangeWarn = false;\r\n");
            out.write("\t\t\t\t  \r\n");
            out.write("\t\t\t\t  function doOnLoad(){\r\n");
            out.write("\t\t\t\t  \tparent.document.title = document.getElementById(\"hfTrackWiseWindowTitle\").value;\r\n");
            out.write("\t\t\t\t  }\r\n");
            out.write("\t\t\t\t  \r\n");
            out.write("\t\t\t \t  function doUnload(){\r\n");
            out.write("\t\t\t \t  \r\n");
            out.write("\t\t\t \t  \t//Call Ajax to release the locks and cleanup the session\r\n");
            out.write("\t\t \t  \t\t//servlet url, pass the search key\r\n");
            out.write("\t\t\t\t\tvar url = \"../ajax?function=closeUserSession\";\r\n");
            out.write("\t\t\t \t  \tvar lastRequest = prepareAjaxRequest(url);\r\n");
            out.write("\t\t\t\t\tlastRequest.send(null);\r\n");
            out.write("\t\t\t\t  }\r\n");
            out.write("\t\t\t\t  \t\r\n");
            out.write("\t\t\t\t   function pageChangeWarning(){\r\n");
            out.write("\t\t\t\t   \t\t//used to warn the user that the page is being unloaded\r\n");
            out.write("\t\t\t\t\t\t//called by onbeforeunload, if this method returns a string, \r\n");
            out.write("\t\t\t\t\t\t//it will show the warning.  \r\n");
            out.write("\t\t\t\t\t\t//allow overriding of the page change warning if a variable is set\r\n");
            out.write("\t\t\t\t\t\tif (_skipPageChangeWarn){\r\n");
            out.write("\t\t\t\t\t\t\t//reset the page change warning\r\n");
            out.write("\t\t\t\t\t\t\t_skipPageChangeWarn = false;\r\n");
            out.write("\t\t\t\t\t\t\treturn;\r\n");
            out.write("\t\t\t\t\t\t}\r\n");
            out.write("\t\t\t\t   \t\treturn '';\r\n");
            out.write("\t\t\t\t   }\r\n");
            out.write("\t\t\t  </script>\r\n");
            out.write("\t\t</head>\t\t\r\n");
            out.write("\t\t<body onload=\"doOnLoad()\" onunload=\"doUnload()\" onbeforeunload=\"return pageChangeWarning()\">\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t\t");
            if (_jspx_meth_tw_005finputHidden_005f0(_jspx_th_tw_005fview_005f0, _jspx_page_context))
              return;
            out.write("\t\r\n");
            out.write("\t\t\r\n");
            out.write("\t\t</body> \t\t \t\t \r\n");
            out.write("\t");
            int evalDoAfterBody = _jspx_th_tw_005fview_005f0.doAfterBody();
            if (evalDoAfterBody != javax.servlet.jsp.tagext.BodyTag.EVAL_BODY_AGAIN)
              break;
          } while (true);
          if (_jspx_eval_tw_005fview_005f0 != javax.servlet.jsp.tagext.Tag.EVAL_BODY_INCLUDE) {
            out = _jspx_page_context.popBody();
          }
        }
        if (_jspx_th_tw_005fview_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return;
        }
        _005fjspx_005ftagPool_005ftw_005fview.reuse(_jspx_th_tw_005fview_005f0);
        _jspx_th_tw_005fview_005f0_reused = true;
      } finally {
        org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005fview_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005fview_005f0_reused);
      }
      out.write("\r\n");
      out.write("</html>\r\n");
      out.write("\t\t");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_tw_005finputHidden_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_tw_005fview_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  tw:inputHidden
    com.sparta.common.view.tag.inputHidden.TWInputHiddenTag _jspx_th_tw_005finputHidden_005f0 = (com.sparta.common.view.tag.inputHidden.TWInputHiddenTag) _005fjspx_005ftagPool_005ftw_005finputHidden_0026_005fvalue_005fid_005fnobody.get(com.sparta.common.view.tag.inputHidden.TWInputHiddenTag.class);
    boolean _jspx_th_tw_005finputHidden_005f0_reused = false;
    try {
      _jspx_th_tw_005finputHidden_005f0.setPageContext(_jspx_page_context);
      _jspx_th_tw_005finputHidden_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_tw_005fview_005f0);
      // /pages/hiddenMainFrame.jsp(39,3) name = id type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005finputHidden_005f0.setId("hfTrackWiseWindowTitle");
      // /pages/hiddenMainFrame.jsp(39,3) name = value type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_tw_005finputHidden_005f0.setValue("#{GlobalMngdBean.windowTitle}");
      int _jspx_eval_tw_005finputHidden_005f0 = _jspx_th_tw_005finputHidden_005f0.doStartTag();
      if (_jspx_th_tw_005finputHidden_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005ftw_005finputHidden_0026_005fvalue_005fid_005fnobody.reuse(_jspx_th_tw_005finputHidden_005f0);
      _jspx_th_tw_005finputHidden_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_tw_005finputHidden_005f0, _jsp_getInstanceManager(), _jspx_th_tw_005finputHidden_005f0_reused);
    }
    return false;
  }
}
